11:17:50 AM: DEBUG [prueba_logging.py:13] Level debug
11:17:50 AM: INFO [prueba_logging.py:14] level info
11:17:50 AM: WARNING [prueba_logging.py:15] level warning
11:17:50 AM: ERROR [prueba_logging.py:16] level error
11:17:50 AM: CRITICAL [prueba_logging.py:17] level critical
02:05:41 PM: DEBUG [Conexion.py:45] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x0000019757258850>
02:06:18 PM: DEBUG [Conexion.py:45] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000001F1F7B78850>
02:10:27 PM: DEBUG [Conexion.py:45] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x00000184AF298850>
02:10:45 PM: DEBUG [Conexion.py:45] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x00000193A8B68850>
02:16:31 PM: ERROR [Conexion.py:62] Error al obtener conexion: maximum recursion depth exceeded while calling a Python object
02:16:31 PM: ERROR [Conexion.py:62] Error al obtener conexion: maximum recursion depth exceeded while calling a Python object
02:18:13 PM: ERROR [Conexion.py:62] Error al obtener conexion: maximum recursion depth exceeded while calling a Python object
02:18:13 PM: ERROR [Conexion.py:62] Error al obtener conexion: maximum recursion depth exceeded while calling a Python object
02:20:54 PM: DEBUG [Conexion.py:45] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x00000244A2B3CA50>
02:21:55 PM: ERROR [Conexion.py:62] Error al obtener conexion: maximum recursion depth exceeded while calling a Python object
02:21:55 PM: ERROR [Conexion.py:62] Error al obtener conexion: maximum recursion depth exceeded while calling a Python object
02:22:01 PM: ERROR [Conexion.py:62] Error al obtener conexion: maximum recursion depth exceeded while calling a Python object
02:22:01 PM: ERROR [Conexion.py:62] Error al obtener conexion: maximum recursion depth exceeded while calling a Python object
02:22:10 PM: ERROR [Conexion.py:62] Error al obtener conexion: maximum recursion depth exceeded while calling a Python object
02:22:16 PM: ERROR [Conexion.py:62] Error al obtener conexion: maximum recursion depth exceeded while calling a Python object
02:23:29 PM: ERROR [Conexion.py:62] Error al obtener conexion: maximum recursion depth exceeded while calling a Python object
02:25:36 PM: ERROR [Conexion.py:61] Error al obtener conexion: maximum recursion depth exceeded while calling a Python object
02:30:52 PM: DEBUG [Conexion.py:45] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000001F0AA450750>
02:31:17 PM: DEBUG [Conexion.py:45] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x0000020B52790090>
02:31:17 PM: ERROR [Conexion.py:61] Error al obtener conexion: maximum recursion depth exceeded while calling a Python object
02:31:57 PM: DEBUG [Conexion.py:45] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x00000259B139C090>
02:31:57 PM: ERROR [Conexion.py:61] Error al obtener conexion: maximum recursion depth exceeded while calling a Python object
02:32:26 PM: DEBUG [Conexion.py:45] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x0000017916D30090>
02:32:26 PM: ERROR [Conexion.py:62] Error al obtener conexion: maximum recursion depth exceeded while calling a Python object
02:34:05 PM: DEBUG [Conexion.py:45] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x00000266276080D0>
02:34:18 PM: DEBUG [Conexion.py:45] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000002A0506D8090>
02:34:18 PM: DEBUG [Conexion.py:55] Conexi√≥n obtenida del pool: <psycopg2.pool.SimpleConnectionPool object at 0x000002A0506D8090>
02:34:45 PM: DEBUG [Conexion.py:45] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000001D0153C8810>
02:34:45 PM: DEBUG [Conexion.py:55] Conexi√≥n obtenida del pool: None
02:34:45 PM: DEBUG [Conexion.py:55] Conexi√≥n obtenida del pool: <psycopg2.pool.SimpleConnectionPool object at 0x000001D0153C8810>
02:38:07 PM: DEBUG [Conexion.py:45] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x0000016493318990>
02:38:07 PM: DEBUG [Conexion.py:55] Conexi√≥n obtenida del pool: None
02:38:07 PM: DEBUG [Conexion.py:55] Conexi√≥n obtenida del pool: <psycopg2.pool.SimpleConnectionPool object at 0x0000016493318990>
02:38:07 PM: DEBUG [Conexion.py:55] Conexi√≥n obtenida del pool: <psycopg2.pool.SimpleConnectionPool object at 0x0000016493318990>
02:38:07 PM: DEBUG [Conexion.py:55] Conexi√≥n obtenida del pool: <psycopg2.pool.SimpleConnectionPool object at 0x0000016493318990>
02:38:07 PM: DEBUG [Conexion.py:55] Conexi√≥n obtenida del pool: <psycopg2.pool.SimpleConnectionPool object at 0x0000016493318990>
02:38:16 PM: DEBUG [Conexion.py:45] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000001DAAB36CA10>
02:38:16 PM: DEBUG [Conexion.py:55] Conexi√≥n obtenida del pool: None
02:38:16 PM: DEBUG [Conexion.py:55] Conexi√≥n obtenida del pool: <psycopg2.pool.SimpleConnectionPool object at 0x000001DAAB36CA10>
02:38:16 PM: DEBUG [Conexion.py:55] Conexi√≥n obtenida del pool: <psycopg2.pool.SimpleConnectionPool object at 0x000001DAAB36CA10>
02:38:16 PM: DEBUG [Conexion.py:55] Conexi√≥n obtenida del pool: <psycopg2.pool.SimpleConnectionPool object at 0x000001DAAB36CA10>
02:38:16 PM: DEBUG [Conexion.py:55] Conexi√≥n obtenida del pool: <psycopg2.pool.SimpleConnectionPool object at 0x000001DAAB36CA10>
02:38:16 PM: DEBUG [Conexion.py:55] Conexi√≥n obtenida del pool: <psycopg2.pool.SimpleConnectionPool object at 0x000001DAAB36CA10>
02:39:45 PM: DEBUG [Conexion.py:45] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x0000021E53EB0B10>
02:39:45 PM: DEBUG [Conexion.py:55] Conexi√≥n obtenida del pool: None
02:39:45 PM: DEBUG [Conexion.py:55] Conexi√≥n obtenida del pool: <psycopg2.pool.SimpleConnectionPool object at 0x0000021E53EB0B10>
02:39:45 PM: DEBUG [Conexion.py:55] Conexi√≥n obtenida del pool: <psycopg2.pool.SimpleConnectionPool object at 0x0000021E53EB0B10>
02:39:45 PM: DEBUG [Conexion.py:55] Conexi√≥n obtenida del pool: <psycopg2.pool.SimpleConnectionPool object at 0x0000021E53EB0B10>
02:39:45 PM: DEBUG [Conexion.py:55] Conexi√≥n obtenida del pool: <psycopg2.pool.SimpleConnectionPool object at 0x0000021E53EB0B10>
02:39:45 PM: DEBUG [Conexion.py:55] Conexi√≥n obtenida del pool: <psycopg2.pool.SimpleConnectionPool object at 0x0000021E53EB0B10>
02:39:45 PM: DEBUG [Conexion.py:55] Conexi√≥n obtenida del pool: <psycopg2.pool.SimpleConnectionPool object at 0x0000021E53EB0B10>
02:39:45 PM: DEBUG [Conexion.py:55] Conexi√≥n obtenida del pool: <psycopg2.pool.SimpleConnectionPool object at 0x0000021E53EB0B10>
02:40:48 PM: DEBUG [Conexion.py:45] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000001CEB8D30B50>
02:40:58 PM: DEBUG [Conexion.py:45] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000001DF0C888950>
02:42:05 PM: DEBUG [Conexion.py:45] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000001DA4B4F8910>
02:44:14 PM: DEBUG [Conexion.py:44] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000002298F038910>
02:45:14 PM: ERROR [Conexion.py:29] Ocurri√≥ un error al obtener el pool 
02:45:51 PM: DEBUG [Conexion.py:26] Creaci√≥n del pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000001AF85DD2310>
02:45:51 PM: DEBUG [Conexion.py:37] Conexi√≥n obtenida del pool: <connection object at 0x000001AF878C4AE0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
02:45:51 PM: DEBUG [Conexion.py:37] Conexi√≥n obtenida del pool: <connection object at 0x000001AF878C4BF0; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
02:45:51 PM: DEBUG [Conexion.py:37] Conexi√≥n obtenida del pool: <connection object at 0x000001AF878C4D00; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
02:45:51 PM: DEBUG [Conexion.py:37] Conexi√≥n obtenida del pool: <connection object at 0x000001AF878C4E10; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
02:45:52 PM: DEBUG [Conexion.py:37] Conexi√≥n obtenida del pool: <connection object at 0x000001AF878C4F20; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0>
02:47:56 PM: DEBUG [Conexion.py:28] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x0000019F2A758710>
02:49:01 PM: DEBUG [Conexion.py:28] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000001F27F432310>
02:49:04 PM: ERROR [conexion.py:28] OcurriÛ un error al obtener el pool 
02:52:32 PM: DEBUG [Conexion.py:28] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000002275FEA2310>
02:52:40 PM: DEBUG [Conexion.py:28] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000002C3BF2D2310>
02:54:54 PM: DEBUG [Conexion.py:28] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x0000026551DB2350>
02:57:09 PM: DEBUG [Conexion.py:28] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x0000017471A22350>
02:57:19 PM: DEBUG [Conexion.py:28] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x0000013841402450>
02:58:00 PM: DEBUG [Conexion.py:28] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000001CE0ED3C7D0>
02:58:07 PM: DEBUG [Conexion.py:28] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000002064CED23D0>
02:58:42 PM: DEBUG [Conexion.py:28] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x00000202A47E87D0>
02:58:42 PM: DEBUG [Conexion.py:40] Conexi√≥n obtenida del pool: <connection object at 0x00000202A6644AE0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
02:58:42 PM: DEBUG [Conexion.py:40] Conexi√≥n obtenida del pool: <connection object at 0x00000202A6644BF0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
02:58:42 PM: DEBUG [Conexion.py:40] Conexi√≥n obtenida del pool: <connection object at 0x00000202A6644D00; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
02:58:42 PM: DEBUG [Conexion.py:40] Conexi√≥n obtenida del pool: <connection object at 0x00000202A6644E10; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
02:58:42 PM: DEBUG [Conexion.py:40] Conexi√≥n obtenida del pool: <connection object at 0x00000202A6644F20; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
02:59:37 PM: DEBUG [Conexion.py:28] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x00000172EC8A8850>
02:59:37 PM: DEBUG [Conexion.py:40] Conexi√≥n obtenida del pool: <connection object at 0x00000172EE724AE0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
02:59:37 PM: DEBUG [Conexion.py:40] Conexi√≥n obtenida del pool: <connection object at 0x00000172EE724BF0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
02:59:37 PM: DEBUG [Conexion.py:40] Conexi√≥n obtenida del pool: <connection object at 0x00000172EE724D00; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
02:59:38 PM: DEBUG [Conexion.py:40] Conexi√≥n obtenida del pool: <connection object at 0x00000172EE724E10; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
02:59:38 PM: DEBUG [Conexion.py:40] Conexi√≥n obtenida del pool: <connection object at 0x00000172EE724F20; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
03:04:20 PM: DEBUG [Conexion.py:27] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x00000223FC9CC350>
03:04:20 PM: DEBUG [Conexion.py:39] Conexi√≥n obtenida del pool: <connection object at 0x00000223FC9208C0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
03:40:02 PM: DEBUG [cursor_del_pool.py:11] Incio del mÈtodo with __enter__
03:41:40 PM: DEBUG [cursor_del_pool.py:11] Incio del mÈtodo with __enter__
03:43:16 PM: DEBUG [cursor_del_pool.py:11] Incio del mÈtodo with __enter__
03:44:06 PM: DEBUG [cursor_del_pool.py:11] Incio del mÈtodo with __enter__
03:44:55 PM: DEBUG [cursor_del_pool.py:11] Incio del mÈtodo with __enter__
03:44:55 PM: DEBUG [Conexion.py:27] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x0000024049C7ED90>
03:44:55 PM: DEBUG [Conexion.py:39] ConexiÛn obtenida del pool: <connection object at 0x000002404BA75580; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
03:44:55 PM: DEBUG [UsuarioDao.py:16] Seleccionando usuarios
03:44:55 PM: DEBUG [cursor_del_pool.py:17] Se ejecuta mÈtodo __exit__
03:44:55 PM: DEBUG [cursor_del_pool.py:24] Commit de la transacciÛn
03:44:55 PM: DEBUG [Conexion.py:45] Regresamos la conexion al pool: <connection object at 0x000002404BA75580; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
03:44:55 PM: INFO [menu_app_usuario.py:17] Usuario: 1 keynerrex keynerdel2015
03:45:41 PM: INFO [menu_app_usuario.py:19] Salimos de la aplicacion
03:53:42 PM: DEBUG [cursor_del_pool.py:11] Incio del mÈtodo with __enter__
03:53:42 PM: DEBUG [Conexion.py:27] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000001DE2CE9F250>
03:53:42 PM: DEBUG [Conexion.py:39] ConexiÛn obtenida del pool: <connection object at 0x000001DE2EC44F20; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
03:53:42 PM: DEBUG [UsuarioDao.py:16] Seleccionando usuarios
03:53:42 PM: DEBUG [cursor_del_pool.py:17] Se ejecuta mÈtodo __exit__
03:53:42 PM: DEBUG [cursor_del_pool.py:24] Commit de la transacciÛn
03:53:42 PM: DEBUG [Conexion.py:45] Regresamos la conexion al pool: <connection object at 0x000001DE2EC44F20; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
03:53:42 PM: INFO [menu_app_usuario.py:18] Usuario: 1 keynerrex keynerdel2015
03:57:54 PM: DEBUG [cursor_del_pool.py:11] Incio del mÈtodo with __enter__
03:57:54 PM: DEBUG [Conexion.py:27] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x0000026485A94F90>
03:57:54 PM: DEBUG [Conexion.py:39] ConexiÛn obtenida del pool: <connection object at 0x00000264859D17A0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
03:57:54 PM: DEBUG [UsuarioDao.py:28] Usuario a insertar: Usuario: None ken 888324
03:57:54 PM: DEBUG [cursor_del_pool.py:17] Se ejecuta mÈtodo __exit__
03:57:54 PM: DEBUG [cursor_del_pool.py:24] Commit de la transacciÛn
03:57:54 PM: DEBUG [Conexion.py:45] Regresamos la conexion al pool: <connection object at 0x00000264859D17A0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
03:57:54 PM: INFO [menu_app_usuario.py:24] Usuarios insertados: 1
03:57:58 PM: DEBUG [cursor_del_pool.py:11] Incio del mÈtodo with __enter__
03:57:58 PM: DEBUG [Conexion.py:39] ConexiÛn obtenida del pool: <connection object at 0x00000264859D17A0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
03:57:58 PM: DEBUG [UsuarioDao.py:16] Seleccionando usuarios
03:57:58 PM: DEBUG [cursor_del_pool.py:17] Se ejecuta mÈtodo __exit__
03:57:58 PM: DEBUG [cursor_del_pool.py:24] Commit de la transacciÛn
03:57:58 PM: DEBUG [Conexion.py:45] Regresamos la conexion al pool: <connection object at 0x00000264859D17A0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
03:57:58 PM: INFO [menu_app_usuario.py:18] Usuario: 1 keynerrex keynerdel2015
03:57:58 PM: INFO [menu_app_usuario.py:18] Usuario: 2 kina 123445
03:57:58 PM: INFO [menu_app_usuario.py:18] Usuario: 3 ken 888324
03:58:19 PM: DEBUG [cursor_del_pool.py:11] Incio del mÈtodo with __enter__
03:58:19 PM: DEBUG [Conexion.py:39] ConexiÛn obtenida del pool: <connection object at 0x00000264859D17A0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
03:58:19 PM: DEBUG [UsuarioDao.py:36] Usuario a actualizar: Usuario: 3 kinayt kina12345
03:58:19 PM: DEBUG [cursor_del_pool.py:17] Se ejecuta mÈtodo __exit__
03:58:19 PM: ERROR [cursor_del_pool.py:20] OcurriÛ una excepciÛn, se hace rollback: 'Usuario' object has no attribute 'pasword' <class 'AttributeError'> <traceback object at 0x0000026483C1F1C0>
03:58:19 PM: DEBUG [Conexion.py:45] Regresamos la conexion al pool: <connection object at 0x00000264859D17A0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
04:00:01 PM: DEBUG [cursor_del_pool.py:11] Incio del mÈtodo with __enter__
04:00:01 PM: DEBUG [Conexion.py:27] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000001BE66394710>
04:00:01 PM: DEBUG [Conexion.py:39] ConexiÛn obtenida del pool: <connection object at 0x000001BE662F17A0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
04:00:01 PM: DEBUG [UsuarioDao.py:36] Usuario a actualizar: Usuario: 3 kinyt 4534g
04:00:01 PM: DEBUG [cursor_del_pool.py:17] Se ejecuta mÈtodo __exit__
04:00:01 PM: DEBUG [cursor_del_pool.py:24] Commit de la transacciÛn
04:00:01 PM: DEBUG [Conexion.py:45] Regresamos la conexion al pool: <connection object at 0x000001BE662F17A0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
04:00:01 PM: INFO [menu_app_usuario.py:31] Usuarios actualizados: 1
04:00:03 PM: DEBUG [cursor_del_pool.py:11] Incio del mÈtodo with __enter__
04:00:03 PM: DEBUG [Conexion.py:39] ConexiÛn obtenida del pool: <connection object at 0x000001BE662F17A0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
04:00:03 PM: DEBUG [UsuarioDao.py:16] Seleccionando usuarios
04:00:03 PM: DEBUG [cursor_del_pool.py:17] Se ejecuta mÈtodo __exit__
04:00:03 PM: DEBUG [cursor_del_pool.py:24] Commit de la transacciÛn
04:00:03 PM: DEBUG [Conexion.py:45] Regresamos la conexion al pool: <connection object at 0x000001BE662F17A0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
04:00:03 PM: INFO [menu_app_usuario.py:18] Usuario: 1 keynerrex keynerdel2015
04:00:03 PM: INFO [menu_app_usuario.py:18] Usuario: 2 kina 123445
04:00:03 PM: INFO [menu_app_usuario.py:18] Usuario: 3 kinyt 4534g
04:00:10 PM: DEBUG [cursor_del_pool.py:11] Incio del mÈtodo with __enter__
04:00:10 PM: DEBUG [Conexion.py:39] ConexiÛn obtenida del pool: <connection object at 0x000001BE662F17A0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
04:00:10 PM: DEBUG [UsuarioDao.py:44] Usuario a eliminar: Usuario: 3 None None
04:00:10 PM: DEBUG [cursor_del_pool.py:17] Se ejecuta mÈtodo __exit__
04:00:10 PM: ERROR [cursor_del_pool.py:20] OcurriÛ una excepciÛn, se hace rollback: 'int' object does not support indexing <class 'TypeError'> <traceback object at 0x000001BE663B7540>
04:00:10 PM: DEBUG [Conexion.py:45] Regresamos la conexion al pool: <connection object at 0x000001BE662F17A0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
04:01:34 PM: DEBUG [cursor_del_pool.py:11] Incio del mÈtodo with __enter__
04:01:34 PM: DEBUG [Conexion.py:27] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000002B0EDC8F210>
04:01:34 PM: DEBUG [Conexion.py:39] ConexiÛn obtenida del pool: <connection object at 0x000002B0EFA35030; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
04:01:34 PM: DEBUG [UsuarioDao.py:44] Usuario a eliminar: Usuario: 4 None None
04:01:34 PM: DEBUG [cursor_del_pool.py:17] Se ejecuta mÈtodo __exit__
04:01:34 PM: ERROR [cursor_del_pool.py:20] OcurriÛ una excepciÛn, se hace rollback: 'int' object does not support indexing <class 'TypeError'> <traceback object at 0x000002B0EDC8F1C0>
04:01:34 PM: DEBUG [Conexion.py:45] Regresamos la conexion al pool: <connection object at 0x000002B0EFA35030; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
04:05:29 PM: DEBUG [cursor_del_pool.py:11] Incio del mÈtodo with __enter__
04:05:29 PM: DEBUG [Conexion.py:27] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x000001ECC792F210>
04:05:29 PM: DEBUG [Conexion.py:39] ConexiÛn obtenida del pool: <connection object at 0x000001ECC96E17A0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
04:05:29 PM: DEBUG [UsuarioDao.py:44] Usuario a eliminar: Usuario: 4 None None
04:05:29 PM: DEBUG [cursor_del_pool.py:17] Se ejecuta mÈtodo __exit__
04:05:29 PM: ERROR [cursor_del_pool.py:20] OcurriÛ una excepciÛn, se hace rollback: 'int' object does not support indexing <class 'TypeError'> <traceback object at 0x000001ECC792F1C0>
04:05:29 PM: DEBUG [Conexion.py:45] Regresamos la conexion al pool: <connection object at 0x000001ECC96E17A0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
04:06:09 PM: DEBUG [cursor_del_pool.py:11] Incio del mÈtodo with __enter__
04:06:09 PM: DEBUG [Conexion.py:27] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x00000236D125F210>
04:06:09 PM: DEBUG [Conexion.py:39] ConexiÛn obtenida del pool: <connection object at 0x00000236D30418B0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
04:06:09 PM: DEBUG [UsuarioDao.py:44] Usuario a eliminar: Usuario: 4 None None
04:06:09 PM: DEBUG [cursor_del_pool.py:17] Se ejecuta mÈtodo __exit__
04:06:09 PM: ERROR [cursor_del_pool.py:20] OcurriÛ una excepciÛn, se hace rollback: 'int' object does not support indexing <class 'TypeError'> <traceback object at 0x00000236D125F1C0>
04:06:09 PM: DEBUG [Conexion.py:45] Regresamos la conexion al pool: <connection object at 0x00000236D30418B0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
04:07:29 PM: DEBUG [cursor_del_pool.py:11] Incio del mÈtodo with __enter__
04:07:29 PM: DEBUG [Conexion.py:27] Creacion pool exitosa: <psycopg2.pool.SimpleConnectionPool object at 0x0000024D26EDF210>
04:07:29 PM: DEBUG [Conexion.py:39] ConexiÛn obtenida del pool: <connection object at 0x0000024D28CC18B0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
04:07:29 PM: DEBUG [UsuarioDao.py:44] Usuario a eliminar: Usuario: 4 None None
04:07:29 PM: DEBUG [cursor_del_pool.py:17] Se ejecuta mÈtodo __exit__
04:07:29 PM: DEBUG [cursor_del_pool.py:24] Commit de la transacciÛn
04:07:29 PM: DEBUG [Conexion.py:45] Regresamos la conexion al pool: <connection object at 0x0000024D28CC18B0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
04:07:29 PM: INFO [menu_app_usuario.py:36] Usuarios eliminados: 1
04:07:34 PM: DEBUG [cursor_del_pool.py:11] Incio del mÈtodo with __enter__
04:07:34 PM: DEBUG [Conexion.py:39] ConexiÛn obtenida del pool: <connection object at 0x0000024D28CC18B0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
04:07:34 PM: DEBUG [UsuarioDao.py:16] Seleccionando usuarios
04:07:34 PM: DEBUG [cursor_del_pool.py:17] Se ejecuta mÈtodo __exit__
04:07:34 PM: DEBUG [cursor_del_pool.py:24] Commit de la transacciÛn
04:07:34 PM: DEBUG [Conexion.py:45] Regresamos la conexion al pool: <connection object at 0x0000024D28CC18B0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
04:07:34 PM: INFO [menu_app_usuario.py:18] Usuario: 1 keynerrex keynerdel2015
04:07:34 PM: INFO [menu_app_usuario.py:18] Usuario: 2 kina 123445
04:08:01 PM: DEBUG [cursor_del_pool.py:11] Incio del mÈtodo with __enter__
04:08:01 PM: DEBUG [Conexion.py:39] ConexiÛn obtenida del pool: <connection object at 0x0000024D28CC18B0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
04:08:01 PM: DEBUG [UsuarioDao.py:16] Seleccionando usuarios
04:08:01 PM: DEBUG [cursor_del_pool.py:17] Se ejecuta mÈtodo __exit__
04:08:01 PM: DEBUG [cursor_del_pool.py:24] Commit de la transacciÛn
04:08:01 PM: DEBUG [Conexion.py:45] Regresamos la conexion al pool: <connection object at 0x0000024D28CC18B0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
04:08:01 PM: INFO [menu_app_usuario.py:18] Usuario: 1 keynerrex keynerdel2015
04:08:01 PM: INFO [menu_app_usuario.py:18] Usuario: 2 kina 123445
04:08:19 PM: DEBUG [cursor_del_pool.py:11] Incio del mÈtodo with __enter__
04:08:19 PM: DEBUG [Conexion.py:39] ConexiÛn obtenida del pool: <connection object at 0x0000024D28CC18B0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
04:08:19 PM: DEBUG [UsuarioDao.py:28] Usuario a insertar: Usuario: None keynerrexyt Keynerdel2015@
04:08:19 PM: DEBUG [cursor_del_pool.py:17] Se ejecuta mÈtodo __exit__
04:08:19 PM: DEBUG [cursor_del_pool.py:24] Commit de la transacciÛn
04:08:19 PM: DEBUG [Conexion.py:45] Regresamos la conexion al pool: <connection object at 0x0000024D28CC18B0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
04:08:19 PM: INFO [menu_app_usuario.py:24] Usuarios insertados: 1
04:08:20 PM: DEBUG [cursor_del_pool.py:11] Incio del mÈtodo with __enter__
04:08:20 PM: DEBUG [Conexion.py:39] ConexiÛn obtenida del pool: <connection object at 0x0000024D28CC18B0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
04:08:20 PM: DEBUG [UsuarioDao.py:16] Seleccionando usuarios
04:08:20 PM: DEBUG [cursor_del_pool.py:17] Se ejecuta mÈtodo __exit__
04:08:20 PM: DEBUG [cursor_del_pool.py:24] Commit de la transacciÛn
04:08:20 PM: DEBUG [Conexion.py:45] Regresamos la conexion al pool: <connection object at 0x0000024D28CC18B0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
04:08:20 PM: INFO [menu_app_usuario.py:18] Usuario: 1 keynerrex keynerdel2015
04:08:20 PM: INFO [menu_app_usuario.py:18] Usuario: 2 kina 123445
04:08:20 PM: INFO [menu_app_usuario.py:18] Usuario: 5 keynerrexyt Keynerdel2015@
04:08:27 PM: DEBUG [cursor_del_pool.py:11] Incio del mÈtodo with __enter__
04:08:27 PM: DEBUG [Conexion.py:39] ConexiÛn obtenida del pool: <connection object at 0x0000024D28CC18B0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
04:08:27 PM: DEBUG [UsuarioDao.py:44] Usuario a eliminar: Usuario: 2 None None
04:08:27 PM: DEBUG [cursor_del_pool.py:17] Se ejecuta mÈtodo __exit__
04:08:27 PM: DEBUG [cursor_del_pool.py:24] Commit de la transacciÛn
04:08:27 PM: DEBUG [Conexion.py:45] Regresamos la conexion al pool: <connection object at 0x0000024D28CC18B0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
04:08:27 PM: INFO [menu_app_usuario.py:36] Usuarios eliminados: 1
04:08:28 PM: DEBUG [cursor_del_pool.py:11] Incio del mÈtodo with __enter__
04:08:28 PM: DEBUG [Conexion.py:39] ConexiÛn obtenida del pool: <connection object at 0x0000024D28CC18B0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
04:08:28 PM: DEBUG [UsuarioDao.py:16] Seleccionando usuarios
04:08:28 PM: DEBUG [cursor_del_pool.py:17] Se ejecuta mÈtodo __exit__
04:08:28 PM: DEBUG [cursor_del_pool.py:24] Commit de la transacciÛn
04:08:28 PM: DEBUG [Conexion.py:45] Regresamos la conexion al pool: <connection object at 0x0000024D28CC18B0; dsn: 'user=postgres password=xxx dbname=test_db host=localhost port=5432', closed: 0>
04:08:28 PM: INFO [menu_app_usuario.py:18] Usuario: 1 keynerrex keynerdel2015
04:08:28 PM: INFO [menu_app_usuario.py:18] Usuario: 5 keynerrexyt Keynerdel2015@
04:08:32 PM: INFO [menu_app_usuario.py:39] Salimos de la aplicacion
